version: "3.2"

services:
  mongodb:
    container_name: mongodb-rent
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - rent-network
  react-app:
    container_name: react-rent-app
    image: react-image
    build:
      context: ./client
      dockerfile: client.Dockerfile
    stdin_open: true
    ports:
      - 3000:3000
    links:
      - server-node
    networks:
      - rent-network
    environment:
      - REACT_APP_BASE_URL=http://server-node:5000
  server-node:
    container_name: server-rent-container
    build:
      context: ./server
      dockerfile: server.Dockerfile
    command: "npm run dev"
    ports:
      - "5000:5000"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - rent-network
    environment:
      - LOCAL_DB_NAME=mongodb-rent

  chat-server-node:
    container_name: chat-server-rent-container
    build:
      context: ./chatServer
      dockerfile: chatServer.Dockerfile
    command: "npm run dev"
    ports:
      - "5001:5001"
    networks:
      - rent-network

volumes:
  data:
networks:
  rent-network:
    driver: bridge
